version: '3.8'
services:
    php-fpm:
        build:
            dockerfile: docker/Dockerfile
            context: ./
            target: php_fpm
            args:
                - XDEBUG
        container_name: ${PROJECT_NAME}-php
        environment:
            PHP_IDE_CONFIG: "serverName=localhost"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/app
        restart: unless-stopped
    nginx:
        image: nginx:stable-alpine
        container_name: ${PROJECT_NAME}-nginx
        volumes:
            - ./public:/app/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/htpasswd:/etc/nginx/htpasswd
        ports:
            - "8090:80"
        restart: unless-stopped
